apiVersion: v1
kind: ConfigMap
metadata:
  name: gamedeals-bot-config
  namespace: gamedeals-bot
data:
  FLARE_SOLVER_URL: "http://flaresolverr:8191"
  CRON_SCHEDULE: "0 */5 * * *"
  SCRAPE_PAGES: "1"
  STORES: "Steam, Ubisoft Store, Epic Games Store, Microsoft Store"
  MIN_DISCOUNT: "0"
  MAX_PRICE: "0"
  MIN_RATING: "0"
  PLATFORMS: ""
  FREE_ONLY: "false"
  MIN_RATING_OVERRIDES: ""
  SILENT_MODE: "false"
