apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gamedeals-bot-data
  namespace: gamedeals-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard  # uncomment to pin to a specific storage class
